
--创建users表开始

DROP TABLE USERS;
-- 创建表
CREATE TABLE USERS(  
  ID INT NOT NULL,  
  USER_NAME VARCHAR(512) NOT NULL,  
  PASSWORD VARCHAR(512) NOT NULL,  
  AGE INT NOT NULL,
  GENDER INT NOT NULL,  
  PRIMARY KEY(ID)  
);  

--创建自增ID，名称为：表名_字段名_SEQ
CREATE SEQUENCE USERID_SEQ
INCREMENT BY 1 -- 每次加几个
START WITH 1 -- 从1开始计数
NOMAXVALUE -- 不设置最大值
NOCYCLE -- 一直累加，不循环
CACHE 10;

-- CREATE TRIGGER
CREATE TRIGGER TG_USERS_INSERT
  BEFORE INSERT ON USERS
  REFERENCING NEW AS NEW OLD AS OLD
  FOR EACH ROW
DECLARE
  NEXTVAL INTEGER;
BEGIN
  SELECT USERID_SEQ.NEXTVAL INTO NEXTVAL FROM DUAL;
  :NEW.ID := NEXTVAL;
END;
/

INSERT INTO USERS(USER_NAME,PASSWORD,AGE,GENDER) VALUES('admin1','a642b889e712dcbcd8ae70e68b9abd79',24,1);
INSERT INTO USERS(USER_NAME,PASSWORD,AGE,GENDER) VALUES('lockedUser','654750cb5d1fc5da28533bc2b405f170',26,0);
INSERT INTO USERS(USER_NAME,PASSWORD,AGE,GENDER) VALUES('buyer1','fa961c287aac9553bc265a4037115a6a',33,0);
INSERT INTO USERS(USER_NAME,PASSWORD,AGE,GENDER) VALUES('seller','caa8898890842fdfcb108a57550a781e',68,1);

SELECT * FROM USERS;

--创建users表结束

--创建demo表开始

DROP TABLE DEMO;
-- 创建表
CREATE TABLE DEMO(  
  ID INT NOT NULL,
  NAME VARCHAR(16) NOT NULL,  
  ITEM_DESCRIPTION VARCHAR(16) NOT NULL,  
  UNIT VARCHAR(16) NOT NULL,  
  REMARK VARCHAR(16) NOT NULL,  
  PRIMARY KEY(ID)  
);  

--创建自增ID，名称为：表名_字段名_SEQ
CREATE SEQUENCE DEMOID_SEQ
INCREMENT BY 1 -- 每次加几个
START WITH 1 -- 从1开始计数
NOMAXVALUE -- 不设置最大值
NOCYCLE -- 一直累加，不循环
CACHE 10;

-- CREATE TRIGGER
CREATE TRIGGER TG_DEMO_INSERT
  BEFORE INSERT ON DEMO
  REFERENCING NEW AS NEW OLD AS OLD
  FOR EACH ROW
DECLARE
  NEXTVAL INTEGER;
BEGIN
  SELECT DEMOID_SEQ.NEXTVAL INTO NEXTVAL FROM DUAL;
  :NEW.ID := NEXTVAL;
END;
/

INSERT INTO DEMO (NAME,ITEM_DESCRIPTION,UNIT,REMARK) VALUES ('电脑','THINKPADE470','台','研发部购买');
INSERT INTO DEMO (NAME,ITEM_DESCRIPTION,UNIT,REMARK) VALUES ('显示器','DELL','个','实施部购买');

SELECT * FROM DEMO;

--创建demo表结束
